export const BASIC_FEATURES = [
    { checked: true, text: 'Ad-Free' },
    { checked: true, text: 'Unlimited Music Streaming' },
    { checked: true, text: '2 Artworks scenes' },
    { checked: true, text: '3 Ambient Sounds' },
    { checked: false, text: 'Priority support' },
    { checked: false, text: 'Save your favorite templates' },
    { checked: false, text: 'Download wallpapers' },
    { checked: false, text: "To-do's" },
    { checked: false, text: 'Notepad' },
    { checked: false, text: 'Insights' },
    { checked: false, text: 'Support mental health organizations*' },
];
export const PREMIUM_FEATURES = [
    { checked: true, text: 'Ad-Free' },
    { checked: true, text: 'Unlimited Music Streaming' },
    { checked: true, accent: '20', text: 'scenes and growing' },
    { checked: true, accent: '15+', text: 'sounds to mix and match to your liking' },
    { checked: true, text: 'Priority support' },
    { checked: true, text: 'Save your favorite templates' },
    { checked: true, text: 'Download wallpapers' },
    { checked: true, text: "To-do's" },
    { checked: true, text: 'Notepad' },
    { checked: true, text: 'Insights' },
    { checked: true, text: 'Support mental health organizations*' },
];
